variable "app-name" {}
variable "env" {}
variable "solution_stack" {}
variable "cname_prefix" {}
variable "ec2-profile" {}
variable "instance_type" {}
variable "loadbalancer" {}
variable "elb-scheme" {}
variable "env_variable" {}
variable "login" {}
variable "max_instance_count" {}
variable "version-label" {}